### ISSUE TITLE
真的很感谢！写的非常好！功能建议。

### ISSUE THREAD

**Issue by MAYBreath** [leestar54/WebWeChatAPI.Net#1]
就是登录后 下次打开能自动记住就好了。。
因为频繁登录怕被ban。

最重要的一点就是群消息获取，无法知道是谁发的消息。。连名字也没有。nickname就是是全部的群人员的昵称啊。。

再次感谢，给了我很大的帮助。

**Comment by leestar54** [comment]
新年快乐

群成员信息需要我们新建个字典主动调用GetBatchGetContactAsync拉取，具体参考demo，有说明，也可以自己尝试用fiddler看看交互过程。

记住上一次登陆信息，这一个功能我这边暂时用不到，因为登陆的号每次都不一样，所以暂时没有开发意向，如果可以的话，欢迎Pull requests

**Comment by MAYBreath** [comment]
春节快乐~
谢谢，群成员信息我根据demo的item.Content，手动截取了fromusername字段，这个字段就可以拿去字典里直接用了。。
主要是我弄不太清楚这个更新同步机制，如果添加了新的联系人或者加了新的群，程序没法识别，新加的item.FromUserName没有在contactDict字典里，而手动添加进去我是调用 client.GetBatchGetContactAsync(item.FromUserName);
因为是异步，我不知道什么时候才算调用完了，用client.IsFinishGetContactList看也是true了，结果在contactDict字典里还是没添加这个新加的群和联系人的fromUsername，希望能指教一下，新加联系人后，何时怎么做才能进行查询这个新联系人的contactDict字典信息。

另外用户唯一识别码不知道是否有头绪？

**Comment by leestar54** [comment]
1、群成员信息可以直接用fromusername，可能是因为该成员是你的好友，所以初始化的联系人的时候自动加载了，否则不是好友的成员是不会在字典里的。

2、client.IsFinishGetContactList是首次登陆的时候通过GetContact函数获取当前联系人列表用的，为私有函数，仅在登陆之后自动调用一次，注意GetContact与BatchGetContact的回调函数是不一样的。

3、BatchGetContact用来主动**拉取**未知联系人信息（只要是字典中不存在的，都可以通过该函数拉取，然后保存到字典中），例如新增的联系人或群，我们可以在系统消息那里做判断，通过GetBatchGetContactAsync拉取新内容，见已更新的demo示例

4、个人信息中uin是不变的，而联系人中username会根据每次登陆的token做hash，所以每次都不一样

**Comment by MAYBreath** [comment]
感谢，根据你的提示已经修改成功了。因为拉取是异步的所以我直接在下面加sleep卡住下面线程了。

client.GetBatchGetContactAsync(item.FromUserName);
Console.WriteLine("新联系人添加中");

//如果检测直到还没新增成功，则等待
while (!contactDict.Keys.Contains(item.FromUserName)) 
{Thread.Sleep(500);
if(拉取超时..)
}
之前这边还没拉取新增成功就去字典里查了。。现在这样就好了

第四点的话，我清楚username每次都会变的，你的意思是web版API无法解决这个唯一标识的问题对吗。。我测试的话，其他联系人的username字典里能获取的 除了昵称，很多几乎都是空的..没有其他可以组合用的。。

**Comment by leestar54** [comment]
不能，之前我也研究过，除了uin，其他都会变，但是联系人uin并没有提供，都为0

**Comment by MAYBreath** [comment]
感谢。目前唯一的办法应该就是给这个用户新增一个唯一的备注吧，但是我看你接口上修改备注的接口
client.RemarkName提示说多次修改会被封。。这个。。能用吗。。多次修改大概修改几个人会有被ban的危险。。(⊙o⊙)…

**Comment by leestar54** [comment]
1、因为有频次限制，短时间内多次调用会被封接口，提示“请勿频繁操作”，过一段时间会解封

2、能用，一分钟调用一次，或者5分钟调用一次（需要自己尝试），应该没问题

**Comment by MAYBreath** [comment]
明白了，感谢，早点休息哦！

**Comment by MAYBreath** [comment]
顺便一提，我更新了最新的测试了下
contactDict[item.FromUserName].MemberDict[content[0]].NickName 
无法正确获取到正确的NickName，显示的都是空的。。


就是新更新的那个DEMO，
Console.WriteLine(contactDict[item.FromUserName].NickName + "：" + contactDict[item.FromUserName].MemberDict[content[0]].NickName + "：" + content[1]);
这行。。

**Comment by leestar54** [comment]
我这调试正常的，你自己也调试看看，不行再主动拉取一次保存。Sent from my Huawei Mobile

**Comment by MAYBreath** [comment]
嗯，我昨天有测试了下也可以，今天再测试就不行了，只保存了键值，member内容是空的。估计会受网络影响，没更新进去。还是得写个没有资料自动拉取的样子。。我看看能不能写个合适的，之前写的用client.GetBatchGetContactAsync拉取会超时，不管怎么拉，contactDict里一直都查不到。

**Comment by leestar54** [comment]
#13 感谢这位同学的提交
