### ISSUE TITLE
发送图片失败

### ISSUE THREAD

**Issue by belain** [leestar54/WebWeChatAPI.Net#10]
你好，我在试用中发现无法给好友发送图片，我追踪了http包，修改了3处问题：
1.ClientMsgId和LocalID现在是17位数字，程序中是13位；
2. "Msg": {} 中的Content程序中未赋值，生成的json是"Msg": {“Content”: null} 我给他赋值后现在是"Msg": {“Content”: ""} ;
3.发送图片Url从：.../cgi-bin/mmwebwx-bin/webwxsendmsgimg?fun=async&f=json&lang=zh_CN&pass_ticket=... 改成了 .../cgi-bin/mmwebwx-bin/webwxsendmsgimg?fun=async&f=json

以上三处小问题我修改后，发送图片步骤的：
 response = httpClient.PostJson<SendMsgResponse>(sendMsgUrl, sendImgMsgRequest);
返回始终是：
{
"BaseResponse": {
"Ret": -1,
"ErrMsg": ""
}
,
"MsgID": "",
"LocalID": ""
}
而图片也未发送成功。

希望能和你共同讨论解决问题。

**Comment by belain** [comment]
github用户名就是我的微信号，请加我。

**Comment by leestar54** [comment]
我这边测试没有问题，另外，示例代码中新增了发送图片的方法示例，默认发送给filehelper【文件传输助手】，自行测试后反馈

**Comment by yf2468** [comment]
我这边发送图片也没问题。

**Comment by yf2468** [comment]
client中的Sync每次耗时26秒左右，这个正常吗？

**Comment by leestar54** [comment]
@yf2468 微信的Sync长连接超时就是30秒左右，正常的，如果有消息就立即返回，没有消息就一直保持连接，超时之后重新发起sync
