### ISSUE TITLE
请问能否读取已关注公众号的信息呢？

### ISSUE THREAD

**Issue by yf2468** [leestar54/WebWeChatAPI.Net#12]
如题，谢谢！

**Comment by leestar54** [comment]
取不到哟，网页版没有此类接口

**Comment by yf2468** [comment]
那请问有没有研究过PC版呢？

**Comment by leestar54** [comment]
没深入研究，只知道大致原理基于duilib注入拦截

**Comment by yf2468** [comment]
duilib不是一个界面的开源项目吗？有没有您知道的PC版开源项目呢？谢谢！

**Comment by yf2468** [comment]
我想了解一下本程序批量获取微信公众号文章的方法 答：通过fiddler获取电脑版的微信公众号访问请求以及response，然后本程序解析resopnse里面的msglist 然后批量获取文章的链接 描述 发布时间 名称等 然后批量插入数据库 记得自己改数据库信息哦 值得注意的是：目前key算法换成一个公众号一个key key有效30min 我觉得用key获取文章历史的没啥意义，当然大家可以只用key来拼出来，获取文章历史列表只需要frommsgid和count 就行，我这里就不写我怎么拼了。
