### ISSUE TITLE
无法自动登录

### ISSUE THREAD

**Issue by xiahb** [leestar54/WebWeChatAPI.Net#19]
大神好，在使用项目时，发现并不能实现热登录，不知道为什么，能否解答一下？cookies已经保存了的

**Comment by xiahb** [comment]
跟踪代码得到的返回消息是：device authinfo invalid

**Comment by leestar54** [comment]
我这边临时测试是正常的，可以自行检查一下，或者具体的复现步骤是什么，删除cookie文件重新登录是否正常？又或者是否是由于长时间未使用该cookie过期导致的？这个我还没测试过。如果是的话欢迎PR~

**Comment by xiahb** [comment]
好吧。原因不是很清楚，我反复测试好几次都无法登录。
在
![image](https://user-images.githubusercontent.com/10097686/60580165-2bbea080-9db7-11e9-9e38-8080a877afdc.png)

![image](https://user-images.githubusercontent.com/10097686/60580088-09c51e00-9db7-11e9-8884-75024cb7d6e8.png)

**Comment by xiahb** [comment]
大神好，今天看了下itchat的源码，发现itchat热登录用的域名是https://login.weixin.qq.com，我用这个域名测试了下就可以了。再次感谢大神提供的项目！

**Comment by leestar54** [comment]
想起来了，之前做测试发现不同时期注册的微信调用的webapi会有些差异，可能是这个原因导致的吧。
建议自行抓包，对比看看差异，做出调整。同时欢迎PR
