### ISSUE TITLE
提示账号不能使用网页版登录是什么原因？

### ISSUE THREAD

**Issue by bebestmaple** [leestar54/WebWeChatAPI.Net#20]
![TIM截图20190801173326](https://user-images.githubusercontent.com/7425640/62282719-a1835e00-b482-11e9-9ea4-a32f0b278554.png)

**Comment by leestar54** [comment]
微信对不同时期的账号做了限制，后期注册的号可能会出现这个情况，你去微信官方也无法登陆的。
也就是说只能使用PC版。

**Comment by bebestmaple** [comment]
我这个账号是微信刚有的时候就注册的了
