### ISSUE TITLE
两周前开始，每天晚上自动登出

### ISSUE THREAD

**Issue by yf2468** [leestar54/WebWeChatAPI.Net#23]
1101错误，大家有这样的情况吗？

**Comment by leestar54** [comment]
以前有遇到过，没分析出原因。有时候不一定是晚上，偶尔也会出现1101的返回码

**Comment by yf2468** [comment]
目前每天晚上都出现，估计是服务器踢人了。

BTW:兄弟有没有其他替代方案呢，非常感谢!
