### ISSUE TITLE
How do you send information to a user regularly？

### ISSUE THREAD

**Issue by vitagreen19** [leestar54/WebWeChatAPI.Net#5]
SendMsgAsync(string msg, string toUserName)
------------------------------------------------------

How to get "toUserName"？
How to add a thread to your program?

Thank you very much.

**Comment by leestar54** [comment]
1、See demo
https://github.com/leestar54/WebWeChatAPI.Net/blob/master/Test/Program.cs
https://github.com/leestar54/WebWeChatAPI.Net/blob/master/Modal/User.cs
GetContactComplete Event can get your Contact List, Contact model inherit from User model, you can use username property to replace toUserName filed

2、You can use timer or thread or something else by yourself and add it anywhere you want

**Comment by vitagreen19** [comment]
it works,thank you.

user.Uin=0?

**Comment by leestar54** [comment]
Yes, the Uin in the contact list item is 0, the Uin property only used in webwxinit method, it will return your user information and the Uin is your unique number, you can use it to distinguish between login users
