### ISSUE TITLE
error message: 请求被中止:未能创建 SSL/TLS 安全通道。

### ISSUE THREAD

**Issue by vitagreen19** [leestar54/WebWeChatAPI.Net#6]
I add a function in Program.cs.

        public static string GetContentFromUrl()
        {
            try
            {
                WebClient client = new WebClient();
                System.Collections.Specialized.NameValueCollection PostVars = new System.Collections.Specialized.NameValueCollection();
                PostVars.Add("PACKET", "test1");
                client.Credentials = CredentialCache.DefaultCredentials;
                Byte[] pageData = client.UploadValues("https://www.abc.com:8888/RCC/VC.ashx", "POST", PostVars);
                string pageHtml = System.Text.Encoding.UTF8.GetString(pageData);
                return pageHtml;
            }
            catch (WebException ex)
            {
                return ex.Message;
            }
        }

and run it in

        private static void Client_ReceiveMsg(object sender, TEventArgs<List<AddMsg>> e)
        {
            foreach (var item in e.Result)
            {
                switch (item.MsgType)
                {
                    case MsgType.MM_DATA_TEXT:
					//自动回复
                                        string s = GetContentFromUrl());
                                        client.SendMsgAsync(s, item.FromUserName);

https://www.abc.com:8888/RCC/VC.ashx   is my service address , it 's ok.

**Comment by leestar54** [comment]
try https://stackoverflow.com/questions/536352/webclient-https-issues

**Comment by vitagreen19** [comment]
But the codes in a new project works.

Best wishes!
