### ISSUE TITLE
Dear leestar54

### ISSUE THREAD

**Issue by vitagreen19** [leestar54/WebWeChatAPI.Net#8]
HttpClient.cs line 44:
ServicePointManager.SecurityProtocol = SecurityProtocolType.Tls12;

Maybe be change to:
ServicePointManager.SecurityProtocol = SecurityProtocolType.Ssl3 | SecurityProtocolType.Tls | SecurityProtocolType.Tls11 | SecurityProtocolType.Tls12;

**Comment by leestar54** [comment]
It is recommended to use the latest security protocol version. The WeChat network API support Tls12. If your website doesn't support Tls12, you should add other protocol types.
![image](https://user-images.githubusercontent.com/6147833/43472568-5671b632-9520-11e8-9e6c-918f8e390f01.png)
