### ISSUE TITLE
关于新增线程

### ISSUE THREAD

**Issue by yf2468** [leestar54/WebWeChatAPI.Net#9]
您好，我在你的TEST项目中模拟您的写法增加了一个类（用于定时采集数据）
            obj.Start();          //定时采集数据类
            client.Start();
            qrForm.ShowDialog();
            Console.ReadLine();
            client.Close();
            client.Logout();
采集都正常，但是就无法在主程序中通过回车执行client.Close()和client.Logout()了，请问您知道原因吗？

**Comment by leestar54** [comment]
请具体描述一下【无法执行】，报错了？没返回值？执行成功无效？需要具体问题具体分析
建议自行单步调试，反馈详细一些

**Comment by yf2468** [comment]
没有报错，只是在console窗口按回车不会退出程序，就像没执行一样。
c#中有当前线程的概念吗？

**Comment by yf2468** [comment]
哦，我弄错了，与我的线程无关。原来直接运行你的源代码就会有这个问题。我看你的语句是回车可以退出程序的，在我这里运行不行。我的环境是WIN10+VS2017，麻烦有空帮忙看看你会不会，谢谢。

**Comment by leestar54** [comment]
示例代码中，qrForm.ShowDialog();会中断主线程，所以需要手动去关掉这个对话框。已优化登陆后自动关闭扫码对话框

**Comment by yf2468** [comment]
谢谢！
